
services:
  user-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - db

  db:
    image: mysql:8.0.1
    restart: always
    environment:
      MYSQL_DATABASE: user_db_local
      MYSQL_USER: root
      MYSQL_PASSWORD: 12Rose#2323
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
