server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/user_db_prod
    username: prod_user
    password: prod_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: WARN