server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://uat-db-server:3306/user_db_uat
    username: uat_user
    password: uat_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: INFO